name: kita_usaha_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/background-2.jpg
    - lib/assets/background-3.png
    - lib/assets/background-login.jpg
    - lib/assets/content-creator-kits.png
    - lib/assets/live-shopping.png
    - lib/assets/logo-kitausaha.png
    - lib/assets/margin-wizard.png
    - lib/assets/open-partnership.png
    - lib/assets/smart-ads.png
    - lib/assets/succes-bundle.png
    - lib/assets/the-circle.png
    - lib/assets/Trade-Insight.png
    - lib/assets/UMKM-Festival.png
