name: kita_usaha_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/background-2.jpg
    - lib/assets/background-3.png
    - lib/assets/background-login.jpg
    - lib/assets/content-creator-kits.png
    - lib/assets/live-shopping.png
    - lib/assets/logo-kitausaha.png
    - lib/assets/margin-wizard.png
    - lib/assets/open-partnership.png
    - lib/assets/smart-ads.png
    - lib/assets/succes-bundle.png
    - lib/assets/the-circle.png
    - lib/assets/Trade-Insight.png
    - lib/assets/UMKM-Festival.png
    - lib/assets/b1.png
    - lib/assets/b2.png
    - lib/assets/b3.jpg
    - lib/assets/b4.png
    - lib/assets/c1.jpg
    - lib/assets/c2.jpg
    - lib/assets/c3.jpg
    - lib/assets/c4.jpg
    - lib/assets/c5.jpg
    - lib/assets/c6.jpg
    - lib/assets/c7.jpg
    - lib/assets/c8.jpg
    - lib/assets/d1.jpg
    - lib/assets/d2.jpg
    - lib/assets/d3.jpg
    - lib/assets/d4.jpg
    - lib/assets/d5.jpg
    - lib/assets/d6.jpg
    - lib/assets/d7.jpg
    - lib/assets/d8.jpg
    - lib/assets/d9.jpg
    - lib/assets/d10.jpg
    - lib/assets/d11.jpg
    - lib/assets/d12.jpg
    - lib/assets/d13.jpg
    - lib/assets/d14.jpg
    - lib/assets/d15.jpg
    - lib/assets/d16.jpg
    - lib/assets/e1.png
    - lib/assets/p1.png